### ISSUE TITLE
Mid-Power-Inputs are Always Low

### ISSUE THREAD

**Issue by foenich** [PPUC/io-boards#2]
If the medium power IO are used as inputs, they are constantly low.
I guess one reason is Line 12 in Switches.cpp: 
`digitalWrite(p, LOW); `
But removing the line didn't help. So maybe I'm wrong or there is a second issue somewhere else.

**Comment by mkalkbrenner** [comment]
Are these the switches 13-16 on IO_16_8_1?

**Comment by foenich** [comment]
Yes, exactly.
